[versions]
vs-core = "0.1.0"

# Kotlin
kotlin-core = "1.8.20"
ksp = "1.8.20-1.0.11"
kotlin-coroutines = "1.7.0-RC"
kotlin-serialization = "1.5.0"

# Android
android-core = "1.7.0"
android-activity-compose = "1.7.1"
android-compose-compiler = "1.4.6"

# Compose
jb-compose = "1.4.0"
decompose = "2.0.0-compose-experimental-alpha-02"

# Logging
logging-log4j = "2.20.0"
logging-slf4j = "1.7.36"
logging-kotlinLogging = "4.0.0-beta-28"

# Other
kodein = "7.20.1"
ktor = "2.3.0"

# Plugins
gradlePlugins-android = "7.4.1" # last version supported by idea comunity 2022.3.3
gradlePlugins-checkUpdates = "0.46.0"
gradlePlugins-detekt = "1.21.0"
gradlePlugins-buildConfig = "3.0.3"


[libraries]
# Core
vs-core-compose = { module = "ru.vs.core:compose", version.ref = "vs-core" }
vs-core-coroutines = { module = "ru.vs.core:coroutines", version.ref = "vs-core" }
vs-core-decompose = { module = "ru.vs.core:decompose", version.ref = "vs-core" }
vs-core-di = { module = "ru.vs.core:di", version.ref = "vs-core" }
vs-core-ktor-server = { module = "ru.vs.core:ktor-server", version.ref = "vs-core" }
vs-core-logging = { module = "ru.vs.core:logging", version.ref = "vs-core" }

# Plugins
gradlePlugins-kotlin-core = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
gradlePlugins-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin-core" }
gradlePlugins-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
gradlePlugins-android = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugins-android" }
gradlePlugins-jb-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jb-compose" }
gradlePlugins-checkUpdates = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradlePlugins-checkUpdates" }
gradlePlugins-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "gradlePlugins-detekt" }
gradlePlugins-buildConfig = { module = "com.github.gmazzo:gradle-buildconfig-plugin", version.ref = "gradlePlugins-buildConfig" }

# Kotlin
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }

# Ktor
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }

# Kodein
kodein-core = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
kodein-android = { module = "org.kodein.di:kodein-di-framework-android-x", version.ref = "kodein" }

# Android
android-core = { module = "androidx.core:core-ktx", version.ref = "android-core" }
android-activity = { module = "androidx.activity:activity-ktx", version.ref = "android-core" }
android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "android-activity-compose" }

# Decompose
decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-jetbrains = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }
decompose-android = { module = "com.arkivanov.decompose:extensions-android", version.ref = "decompose" }

# Logging
logging-kotlinLogging-core = { module = "io.github.oshai:kotlin-logging", version.ref = "logging-kotlinLogging" }
logging-log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "logging-log4j" }
logging-log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "logging-log4j" }
logging-log4j-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "logging-log4j" }
logging-slf4j = { module = "org.slf4j:slf4j-api", version.ref = "logging-slf4j" }

# Code generation
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

# Oher
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "gradlePlugins-detekt" }
