name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  assemble:
    name: assemble
    runs-on: macos-12
    timeout-minutes: 60
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/workflows/shared/setup-java.yml

      - name: Run gradle
        run: >-
          ./gradlew 
          assemble
          --stacktrace
          --no-configuration-cache