name: Publication to Github maven

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Run gradle
        env:
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
        run: >-
          ./gradlew 
          :core-build-logic:publish
          publish
          -Pru.vs.core.version=${{ github.event.inputs.version }}
          -Pru.vs.core.mvn.user=vsum
          --stacktrace