name: Publication to Github maven

on:
  workflow_dispatch:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Run gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          ./gradlew publish