on:
  workflow_call:

jobs:
  setup-java:
    runs-on: macos-12
    timeout-minutes: 5
    steps:
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 21
        cache: gradle
